# Generated by Django 3.2 on 2025-03-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskjob',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='taskjob',
            name='start_date',
            field=models.DateField(),
        ),
    ]
