# Generated by Django 3.2 on 2025-03-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20250301_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskschedule',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='endTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='startTime',
            field=models.TimeField(null=True),
        ),
    ]
