# Generated by Django 3.2 on 2025-03-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20250302_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskjob',
            name='generated',
            field=models.BooleanField(default=False),
        ),
    ]
