# Generated by Django 3.2 on 2025-03-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskjob_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskschedule',
            name='content_generated',
            field=models.BooleanField(default=False),
        ),
    ]
