# Generated by Django 5.1.7 on 2025-03-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskschedule_content_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskschedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='taskschedule',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='accessRecord',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='taskschedule',
            name='exitRecord',
            field=models.DateTimeField(null=True),
        ),
    ]
