# Generated by Django 5.1.7 on 2025-03-30 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_taskschedule_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSectionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionIndex', models.IntegerField()),
                ('questions', models.JSONField()),
                ('answers', models.JSONField()),
                ('marks', models.IntegerField()),
                ('type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('essay', 'Essay'), ('code', 'Code')], default='mcq', max_length=10)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_tests', to='tasks.taskschedule')),
            ],
        ),
    ]
